bandit.wait_for_unit("multi-user.target")
bandit.succeed("systemctl --failed --no-pager")
bandit.wait_for_unit("NetworkManager.service")
bandit.succeed("systemctl is-active NetworkManager")
bandit.succeed("id vino")
bandit.succeed("groups vino | grep -q wheel")
bandit.succeed("groups vino | grep -q networkmanager")
bandit.succeed("which fish")
bandit.succeed("su -l vino -c 'fish --version'")
bandit.succeed("su -l vino -c 'nvim --version'")
bandit.succeed("su -l vino -c 'git --version'")
bandit.succeed("grep 'flakes' /etc/nix/nix.conf")
bandit.succeed("systemctl is-enabled pipewire.socket")
bandit.wait_for_unit("systemd-resolved.service")
bandit.succeed("systemctl is-enabled bluetooth.service")
bandit.succeed("grep 'auto-optimise-store' /etc/nix/nix.conf")
